// Peta di-generate dari gambar peta asli (public/assets/WhatsApp Image ...jpeg).
// Grid 32 x 18 tile, 1 tile = 40px pada kanvas game 1280 x 720.
//   #  = tembok tepi (memantulkan peluru)   W = tembok abu-abu (memantulkan peluru)
//   C  = peti oranye (hancur/meledak)        I = es (licin)      S = pasir (lambat)
export const TILE = 40
export const GAME_W = 1280
export const GAME_H = 720

export const MAPS = [
  {
    id: 1,
    name: "Tactical Grid Alpha",
    preview: "/assets/WhatsApp Image 2026-10-02 at 1.29.43 PM.jpeg",
    floor: '/assets/maps/map1-floor.jpg',
    wallTile: '/assets/maps/map1-wall.png',
    crateTile: '/assets/maps/map1-crate.png',
    grid: [
      '################################',
      '#..............................#',
      '#..CC.....W..........W.....CC..#',
      '#..C......W..WW..WW..W......C..#',
      '#.........W..W....W..W.........#',
      '#..WW..C.......CC.......C..WW..#',
      '#..W...C...WW......WW...C...W..#',
      '#......C...W........W...C......#',
      '#......W................W......#',
      '#......W................W......#',
      '#......C...W........W...C......#',
      '#..W...C...WW......WW...C...W..#',
      '#..WW..C.......CC.......C..WW..#',
      '#.........W..W....W..W.........#',
      '#..C......W..WW..WW..W......C..#',
      '#..CC.....W..........W.....CC..#',
      '#..............................#',
      '################################',
    ],
    // spawn: [x, y, sudut]  (sudut 0 = hadap atas, 90 = kanan)
    spawns: {
      '1v1': [[100, 360, 90], [1180, 360, 270]],
      '2v2': [[260, 140, 90], [260, 580, 90], [1020, 140, 270], [1020, 580, 270]],
      'ffa': [[260, 140, 135], [1020, 140, 225], [260, 580, 45], [1020, 580, 315]],
    },
  },
  {
    id: 2,
    name: "Ice Fortress Beta",
    preview: "/assets/WhatsApp Image 2026-10-02 at 1.29.53 PM.jpeg",
    floor: '/assets/maps/map2-floor.jpg',
    wallTile: '/assets/maps/map2-wall.png',
    crateTile: '/assets/maps/map2-crate.png',
    grid: [
      '################################',
      '#.....I..................I.....#',
      '#.CC..II...WW......WW...II..CC.#',
      '#.C........W........W........C.#',
      '#....WW.....II....II.....WW....#',
      '#....W....C.II.CC.II.C....W....#',
      '#I.......CC..........CC.......I#',
      '#II...WW................WW...II#',
      '#I....W.....C......C.....W....I#',
      '#I....W.....C......C.....W....I#',
      '#II...WW................WW...II#',
      '#I.......CC..........CC.......I#',
      '#....W....C.II.CC.II.C....W....#',
      '#....WW.....II....II.....WW....#',
      '#.C........W........W........C.#',
      '#.CC..II...WW......WW...II..CC.#',
      '#.....I..................I.....#',
      '################################',
    ],
    // spawn: [x, y, sudut]  (sudut 0 = hadap atas, 90 = kanan)
    spawns: {
      '1v1': [[100, 360, 90], [1180, 360, 270]],
      '2v2': [[140, 220, 90], [140, 500, 90], [1140, 220, 270], [1140, 500, 270]],
      'ffa': [[140, 220, 135], [1140, 220, 225], [140, 500, 45], [1140, 500, 315]],
    },
  },
  {
    id: 3,
    name: "Desert Dunes Gamma",
    preview: "/assets/WhatsApp Image 2026-10-02 at 1.30.04 PM.jpeg",
    floor: '/assets/maps/map3-floor.jpg',
    wallTile: '/assets/maps/map3-wall.png',
    crateTile: '/assets/maps/map3-crate.png',
    grid: [
      '################################',
      '#.......SS............SS.......#',
      '#.......SSS..W....W..SSS.......#',
      '#.......S...WW.CC.WW...S.......#',
      '#..CC.........C..C.........CC..#',
      '#..C..WW...SS......SS...WW..C..#',
      '#.....W...SSS......SSS...W.....#',
      '#.........SS.WW..WW.SS.........#',
      '#...C.......W......W.......C...#',
      '#...C.......W......W.......C...#',
      '#.........SS.WW..WW.SS.........#',
      '#.....W...SSS......SSS...W.....#',
      '#..C..WW...SS......SS...WW..C..#',
      '#..CC.........C..C.........CC..#',
      '#.......S...WW.CC.WW...S.......#',
      '#.......SSS..W....W..SSS.......#',
      '#.......SS............SS.......#',
      '################################',
    ],
    // spawn: [x, y, sudut]  (sudut 0 = hadap atas, 90 = kanan)
    spawns: {
      '1v1': [[100, 100, 135], [1180, 620, 315]],
      '2v2': [[100, 100, 135], [100, 620, 45], [1180, 100, 225], [1180, 620, 315]],
      'ffa': [[100, 100, 135], [1180, 100, 225], [100, 620, 45], [1180, 620, 315]],
    },
  },
  {
    id: 4,
    name: "Night Bastion Delta",
    preview: "/assets/WhatsApp Image 2026-10-02 at 1.30.17 PM.jpeg",
    floor: '/assets/maps/map4-floor.jpg',
    wallTile: '/assets/maps/map4-wall.png',
    crateTile: '/assets/maps/map4-crate.png',
    grid: [
      '################################',
      '#..............................#',
      '#....C....W..........W....C....#',
      '#.....C...W.WW....WW.W...C.....#',
      '#..WW.....W.W......W.W.....WW..#',
      '#..W...CC.....C..C.....CC...W..#',
      '#......W...WW.C..C.WW...W......#',
      '#..C...W..W..........W..W...C..#',
      '#.....WW..W..........W..WW.....#',
      '#.....WW..W..........W..WW.....#',
      '#..C...W..W..........W..W...C..#',
      '#......W...WW.C..C.WW...W......#',
      '#..W...CC.....C..C.....CC...W..#',
      '#..WW.....W.W......W.W.....WW..#',
      '#.....C...W.WW....WW.W...C.....#',
      '#....C....W..........W....C....#',
      '#..............................#',
      '################################',
    ],
    // spawn: [x, y, sudut]  (sudut 0 = hadap atas, 90 = kanan)
    spawns: {
      '1v1': [[100, 100, 135], [1180, 620, 315]],
      '2v2': [[100, 100, 135], [100, 620, 45], [1180, 100, 225], [1180, 620, 315]],
      'ffa': [[100, 100, 135], [1180, 100, 225], [100, 620, 45], [1180, 620, 315]],
    },
  },
]

export const getMap = (id) => MAPS.find((m) => m.id === id) || MAPS[0]
